/**
 * `declaragent capabilities gen --peer <id> [--out <dir>]`
 *
 * Reads `rpc-peers.yaml` → resolves the target peer's `capabilities.yaml`
 * (via its `agent://<id>` path inside the enclosing fleet, or a free
 * filesystem path via `--capabilities <path>`) → emits a deterministic
 * TypeScript file under `generated/<peer-id>.ts` with per-capability
 * `Request` / `Response` type declarations.
 *
 * The emitter is hand-rolled (no `json-schema-to-typescript` dep) to
 * keep the CLI dependency graph tight and guarantee byte-stable output
 * across runs — important for diff stability when the generated file is
 * checked into the caller's repo.
 *
 * @since 1.2.0 — Enterprise Production Plan §3 Item #11
 */

import { mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, isAbsolute, join, resolve } from 'node:path';
import type { CapabilitiesConfig, CapabilityDefinition } from '@declaragent/core';
import { parseCapabilitiesConfig } from '@declaragent/core';
import { parse as parseYaml } from 'yaml';

export interface CapabilitiesGenArgs {
  peer?: string;
  /** Override: direct path to the capabilities.yaml to codegen from. */
  capabilities?: string;
  /** Directory that houses the peer's `capabilities.yaml`. */
  peerRoot?: string;
  out?: string;
  json?: boolean;
}

export interface CapabilitiesGenIo {
  out: (s: string) => void;
  err: (s: string) => void;
  cwd?: string;
}

export async function capabilitiesGen(
  args: CapabilitiesGenArgs,
  io?: CapabilitiesGenIo,
): Promise<number> {
  const writeOut = io?.out ?? ((s) => process.stdout.write(s));
  const writeErr = io?.err ?? ((s) => process.stderr.write(s));
  const cwd = io?.cwd ?? process.cwd();

  const capsPath = resolveCapabilitiesPath(args, cwd);
  if (!capsPath) {
    writeErr(
      'usage: declaragent capabilities gen --peer <agent-id> [--out <dir>]\n' +
        '   or: declaragent capabilities gen --capabilities <path> [--out <dir>]\n',
    );
    return 1;
  }

  let rawYaml: string;
  try {
    rawYaml = readFileSync(capsPath, 'utf-8');
  } catch (err) {
    writeErr(
      `capabilities-gen: cannot read ${capsPath}: ${err instanceof Error ? err.message : String(err)}\n`,
    );
    return 1;
  }

  let parsed: unknown;
  try {
    parsed = parseYaml(rawYaml);
  } catch (err) {
    writeErr(
      `capabilities-gen: invalid YAML in ${capsPath}: ${err instanceof Error ? err.message : String(err)}\n`,
    );
    return 1;
  }

  let config: CapabilitiesConfig;
  try {
    const loaded = parseCapabilitiesConfig(parsed);
    config = loaded.config;
  } catch (err) {
    writeErr(
      `capabilities-gen: ${capsPath} is invalid: ${err instanceof Error ? err.message : String(err)}\n`,
    );
    return 1;
  }

  const peerId = peerIdFromAgentAddress(config.agent);
  const outDir = args.out ? resolveAgainst(cwd, args.out) : join(cwd, 'generated');
  const outFile = join(outDir, `${peerId}.ts`);

  const source = emitTypes(config);
  mkdirSync(dirname(outFile), { recursive: true });
  writeFileSync(outFile, source, 'utf-8');

  if (args.json) {
    writeOut(
      `${JSON.stringify(
        {
          peer: peerId,
          capabilities: config.capabilities.map((c) => c.name),
          outFile,
        },
        null,
        2,
      )}\n`,
    );
  } else {
    writeOut(
      `✓ wrote ${outFile} (${config.capabilities.length} capabilit${
        config.capabilities.length === 1 ? 'y' : 'ies'
      })\n`,
    );
  }
  return 0;
}

function resolveCapabilitiesPath(args: CapabilitiesGenArgs, cwd: string): string | undefined {
  if (args.capabilities) return resolveAgainst(cwd, args.capabilities);
  if (!args.peer) return undefined;
  // Peer resolution strategy: look under `<cwd>/agents/<peer>/capabilities.yaml`
  // (fleet-starter layout) first; otherwise honour `--peer-root <dir>`.
  const root = args.peerRoot ?? join(cwd, 'agents', args.peer);
  return join(resolveAgainst(cwd, root), 'capabilities.yaml');
}

function resolveAgainst(cwd: string, p: string): string {
  return isAbsolute(p) ? p : resolve(cwd, p);
}

function peerIdFromAgentAddress(addr: string): string {
  return addr.replace(/^agent:\/\//, '');
}

// ── Codegen ────────────────────────────────────────────────────────────────

/**
 * Emit deterministic TypeScript for every capability in `config`. Exports:
 *   - `export type <Capability>Request`
 *   - `export type <Capability>Response`
 *   - `export interface Capabilities` keyed by capability name.
 *
 * Every schema's output is ordered by the source object's key order, not
 * insertion order of the generator. That makes the file hash-stable: same
 * schema → identical bytes on every run.
 */
export function emitTypes(config: CapabilitiesConfig): string {
  const lines: string[] = [];
  lines.push('// AUTO-GENERATED by `declaragent capabilities gen`.');
  lines.push(`// Source: ${config.agent}`);
  lines.push(`// Capabilities: ${config.capabilities.map((c) => c.name).join(', ')}`);
  lines.push('// DO NOT EDIT — re-run the command to refresh.');
  lines.push('');
  for (const cap of config.capabilities) {
    emitCapability(cap, lines);
  }
  lines.push('export interface Capabilities {');
  for (const cap of config.capabilities) {
    const tName = capabilityTypeName(cap.name);
    lines.push(
      `  ${JSON.stringify(cap.name)}: { request: ${tName}Request; response: ${tName}Response };`,
    );
  }
  lines.push('}');
  lines.push('');
  return lines.join('\n');
}

function emitCapability(cap: CapabilityDefinition, lines: string[]): void {
  const tName = capabilityTypeName(cap.name);
  if (cap.description) {
    lines.push('/**');
    for (const ln of cap.description.split('\n')) lines.push(` * ${ln}`);
    lines.push(' */');
  }
  lines.push(`export type ${tName}Request = ${renderType(cap.inputSchema, 0)};`);
  lines.push('');
  lines.push(`export type ${tName}Response = ${renderType(cap.outputSchema, 0)};`);
  lines.push('');
}

function capabilityTypeName(name: string): string {
  // `review-pr` → `ReviewPr`. Preserve case of the source `name` token
  // exactly — this is a determinism-sensitive path.
  return name
    .split(/[^a-zA-Z0-9]+/)
    .filter((s) => s.length > 0)
    .map((s) => s.charAt(0).toUpperCase() + s.slice(1))
    .join('');
}

/**
 * JSON Schema → TypeScript type expression. Scope matches
 * `capability-validator.ts`: covers the keywords the runtime understands
 * + falls back to `unknown` for anything the emitter can't prove.
 *
 * Deterministic: every object property is emitted in sorted order, so
 * re-runs produce byte-identical output regardless of how the YAML was
 * tokenized.
 */
export function renderType(schema: unknown, depth: number): string {
  if (schema === undefined || schema === null) return 'unknown';
  if (schema === true) return 'unknown';
  if (schema === false) return 'never';
  if (typeof schema !== 'object') return 'unknown';
  const obj = schema as Record<string, unknown>;

  // $ref resolution is not threaded through here — the codegen emits the
  // ref's *target* inline when the caller (v1.2+) pre-expands references.
  // For now, any remaining $ref becomes `unknown` with a comment.
  if (typeof obj.$ref === 'string') return `unknown /* $ref: ${obj.$ref} */`;

  if (Array.isArray(obj.enum)) {
    return obj.enum
      .map((v) =>
        typeof v === 'string' || typeof v === 'number' || typeof v === 'boolean' || v === null
          ? JSON.stringify(v)
          : 'unknown',
      )
      .join(' | ');
  }
  if ('const' in obj) {
    const c = obj.const;
    if (typeof c === 'string' || typeof c === 'number' || typeof c === 'boolean' || c === null) {
      return JSON.stringify(c);
    }
    return 'unknown';
  }
  if (Array.isArray(obj.oneOf)) {
    return obj.oneOf.map((s) => renderType(s, depth)).join(' | ');
  }
  if (Array.isArray(obj.anyOf)) {
    return obj.anyOf.map((s) => renderType(s, depth)).join(' | ');
  }
  if (Array.isArray(obj.allOf)) {
    return obj.allOf.map((s) => renderType(s, depth)).join(' & ');
  }

  const types = Array.isArray(obj.type)
    ? (obj.type as string[])
    : typeof obj.type === 'string'
      ? [obj.type]
      : undefined;

  if (!types || types.length === 0) return 'unknown';
  if (types.length > 1) {
    return types.map((t) => renderType({ ...obj, type: t }, depth)).join(' | ');
  }

  const t = types[0];
  switch (t) {
    case 'string':
      if (typeof obj.format === 'string') return `string /* format: ${obj.format} */`;
      return 'string';
    case 'integer':
    case 'number':
      return 'number';
    case 'boolean':
      return 'boolean';
    case 'null':
      return 'null';
    case 'array': {
      const inner = renderType(obj.items, depth + 1);
      return `Array<${inner}>`;
    }
    case 'object': {
      return renderObject(obj, depth);
    }
    default:
      return 'unknown';
  }
}

function renderObject(obj: Record<string, unknown>, depth: number): string {
  const props =
    obj.properties && typeof obj.properties === 'object'
      ? (obj.properties as Record<string, unknown>)
      : {};
  const required = new Set(Array.isArray(obj.required) ? (obj.required as string[]) : []);

  const keys = Object.keys(props).sort(); // determinism guarantee
  const indent = '  '.repeat(depth + 1);
  const closeIndent = '  '.repeat(depth);

  if (keys.length === 0) {
    // Open-shape object.
    if (obj.additionalProperties === false) return '{}';
    if (typeof obj.additionalProperties === 'object' && obj.additionalProperties !== null) {
      const vt = renderType(obj.additionalProperties, depth + 1);
      return `Record<string, ${vt}>`;
    }
    return 'Record<string, unknown>';
  }

  const lines: string[] = ['{'];
  for (const key of keys) {
    const subSchema = props[key];
    const desc = extractDescription(subSchema);
    if (desc) {
      for (const ln of desc.split('\n')) lines.push(`${indent}/** ${ln} */`);
    }
    const opt = required.has(key) ? '' : '?';
    const rendered = renderType(subSchema, depth + 1);
    // Quote keys that aren't valid identifiers.
    const propKey = /^[A-Za-z_$][A-Za-z0-9_$]*$/.test(key) ? key : JSON.stringify(key);
    lines.push(`${indent}${propKey}${opt}: ${rendered};`);
  }
  if (obj.additionalProperties === false) {
    // Deliberately emit nothing — closed shape is implied by the explicit
    // property list. We could emit an index signature of `never` but that
    // interacts badly with exact types.
  } else if (typeof obj.additionalProperties === 'object' && obj.additionalProperties !== null) {
    const vt = renderType(obj.additionalProperties, depth + 1);
    lines.push(`${indent}[key: string]: ${vt};`);
  }
  lines.push(`${closeIndent}}`);
  return lines.join('\n');
}

function extractDescription(schema: unknown): string | undefined {
  if (typeof schema !== 'object' || schema === null) return undefined;
  const d = (schema as Record<string, unknown>).description;
  return typeof d === 'string' && d.length > 0 ? d : undefined;
}
