import {
  existsSync,
  mkdirSync,
  readFileSync as nodeReadFileSync,
  writeFileSync as nodeWriteFileSync,
} from 'node:fs';
import { dirname, join } from 'node:path';

/**
 * Stub template content for slice 4. Each entry is the minimal skeleton a
 * generated project needs so the verify step has a plausible `agent.yaml`
 * to point at.
 *
 * TODO: replace stubs with real templates from templates/<name>/ once
 * slice 5 lands. The function signature + keyed shape are stable.
 */
export const TEMPLATE_NAMES = [
  'concierge',
  'oncall-escalator',
  'pr-review',
  'kafka-pipeline',
  'multi-tenant-starter',
] as const;

export type TemplateName = (typeof TEMPLATE_NAMES)[number];

export function isTemplateName(value: string): value is TemplateName {
  return (TEMPLATE_NAMES as readonly string[]).includes(value);
}

interface TemplateStub {
  /** One-line description shown in the picker. */
  description: string;
  /** `agent.yaml` body template — `{{provider}}` placeholder is substituted. */
  agentYaml: string;
  /** `.env.example` body template — `{{envVar}}` placeholder is substituted. */
  envExample: string;
  /** `README.md` body. */
  readme: string;
}

const TEMPLATES: Record<TemplateName, TemplateStub> = {
  concierge: {
    description: 'Minimal Slack Q&A bot. One channel, one skill.',
    agentYaml: `# declaragent concierge — minimal Q&A bot scaffold
name: concierge
provider: {{provider}}
skills:
  - concierge
`,
    envExample: `# Credentials for the concierge template.
{{envVar}}=
`,
    readme: `# concierge

Minimal Q&A agent scaffold generated by \`declaragent init\`.

\`\`\`
declaragent auth login
declaragent
\`\`\`
`,
  },
  'oncall-escalator': {
    description: 'Alertmanager webhook → Slack DM on-call escalator.',
    agentYaml: `# declaragent oncall-escalator — webhook → Slack DM scaffold
name: oncall-escalator
provider: {{provider}}
sources:
  - type: webhook
    id: alertmanager
`,
    envExample: `# Credentials for the oncall-escalator template.
{{envVar}}=
`,
    readme: `# oncall-escalator

Webhook-driven escalation agent scaffold.

\`\`\`
declaragent source list
declaragent daemon
\`\`\`
`,
  },
  'pr-review': {
    description: 'GitHub PR reviewer that posts inline comments.',
    agentYaml: `# declaragent pr-review — GitHub PR reviewer scaffold
name: pr-review
provider: {{provider}}
plugins:
  - "@declaragent/plugin-github"
`,
    envExample: `# Credentials for the pr-review template.
{{envVar}}=
GITHUB_TOKEN=
`,
    readme: `# pr-review

Automated PR review agent scaffold.

\`\`\`
declaragent plugin list
declaragent
\`\`\`
`,
  },
  'kafka-pipeline': {
    description: 'Kafka source + JSON-path routing + daily token budget.',
    agentYaml: `# declaragent kafka-pipeline — streaming pipeline scaffold
name: kafka-pipeline
provider: {{provider}}
sources:
  - type: kafka
    id: ingest
`,
    envExample: `# Credentials for the kafka-pipeline template.
{{envVar}}=
KAFKA_BROKERS=
`,
    readme: `# kafka-pipeline

Kafka-driven pipeline agent scaffold.

\`\`\`
declaragent source list
declaragent daemon
\`\`\`
`,
  },
  'multi-tenant-starter': {
    description: 'Per-tenant routing + quotas + residency primitives.',
    agentYaml: `# declaragent multi-tenant-starter — per-tenant scaffold
name: multi-tenant-starter
provider: {{provider}}
tenancy:
  configPath: ./tenants.yaml
`,
    envExample: `# Credentials for the multi-tenant-starter template.
{{envVar}}=
`,
    readme: `# multi-tenant-starter

Multi-tenant agent scaffold.

\`\`\`
declaragent tenants list
declaragent daemon
\`\`\`
`,
  },
};

export function listTemplates(): ReadonlyArray<{ name: TemplateName; description: string }> {
  return TEMPLATE_NAMES.map((name) => ({ name, description: TEMPLATES[name].description }));
}

export function getTemplateDescription(name: TemplateName): string {
  return TEMPLATES[name].description;
}

/** Minimal FS surface the unpacker needs. Tests inject an in-memory map. */
export interface UnpackFS {
  exists: (path: string) => boolean;
  writeFile: (path: string, contents: string) => void;
  readFile?: (path: string) => string;
}

const DEFAULT_FS: UnpackFS = {
  exists: (p) => existsSync(p),
  writeFile: (p, c) => {
    mkdirSync(dirname(p), { recursive: true });
    nodeWriteFileSync(p, c, 'utf8');
  },
  readFile: (p) => nodeReadFileSync(p, 'utf8'),
};

export interface UnpackOptions {
  template: TemplateName;
  outDir: string;
  providerId: string;
  /** Env var for the chosen provider (e.g. `ANTHROPIC_API_KEY`). */
  providerEnvVar: string;
  force: boolean;
  multiTenant: boolean;
  /** Used only when `multiTenant` is true. */
  tenantId?: string;
}

export interface UnpackResult {
  written: string[];
  skipped: string[];
}

export class TemplateUnpackError extends Error {
  constructor(
    message: string,
    readonly path: string,
  ) {
    super(message);
    this.name = 'TemplateUnpackError';
  }
}

/**
 * Writes the stubbed template skeleton into `outDir`. Pure except for the
 * injected `fs` handle — tests pass a fake backed by a `Map`.
 *
 * Idempotency: every target is checked with `exists`; unless `force`, any
 * collision aborts with `TemplateUnpackError` before the first write.
 */
export function unpackTemplate(opts: UnpackOptions, fs: UnpackFS = DEFAULT_FS): UnpackResult {
  const stub = TEMPLATES[opts.template];
  const targets: Array<{ path: string; contents: string }> = [
    {
      path: join(opts.outDir, 'agent.yaml'),
      contents: stub.agentYaml.replace('{{provider}}', opts.providerId),
    },
    {
      path: join(opts.outDir, '.env.example'),
      contents: stub.envExample.replace('{{envVar}}', opts.providerEnvVar),
    },
    {
      path: join(opts.outDir, 'README.md'),
      contents: stub.readme,
    },
    // Empty project-scope MCP config so teams can share a git-tracked
    // list of servers the agent needs. `declaragent mcp add --scope
    // project` appends to this file.
    {
      path: join(opts.outDir, '.mcp.json'),
      contents: `${JSON.stringify({ version: 1, servers: [] }, null, 2)}\n`,
    },
  ];
  if (opts.multiTenant) {
    const tenantId = opts.tenantId ?? 'default';
    targets.push({
      path: join(opts.outDir, 'tenants.yaml'),
      contents: `strategy:
  bus: per-tenant
tenants:
  - id: ${tenantId}
`,
    });
  }

  if (!opts.force) {
    for (const t of targets) {
      if (fs.exists(t.path)) {
        throw new TemplateUnpackError(
          `refusing to overwrite "${t.path}" — pass --force to replace it.`,
          t.path,
        );
      }
    }
  }

  const written: string[] = [];
  const skipped: string[] = [];
  for (const t of targets) {
    if (!opts.force && fs.exists(t.path)) {
      skipped.push(t.path);
      continue;
    }
    fs.writeFile(t.path, t.contents);
    written.push(t.path);
  }
  return { written, skipped };
}
