#!/usr/bin/env bun
/**
 * Emit `src/version.ts` with the CLI's own version number.
 *
 * Runs as a prebuild step (see `packages/cli/package.json → scripts.build`).
 * The generated file is git-tracked so cloned checkouts build without
 * needing this script to have run first; the build always refreshes it
 * so a stale constant never ships.
 */
import { readFileSync, writeFileSync } from 'node:fs';
import { join, resolve } from 'node:path';

const PKG_ROOT = resolve(import.meta.dir, '..');
const pkg = JSON.parse(readFileSync(join(PKG_ROOT, 'package.json'), 'utf-8')) as {
  version: string;
};
const out = join(PKG_ROOT, 'src', 'version.ts');

const body = `// AUTO-GENERATED by scripts/write-version.ts — do NOT edit by hand.
// Re-emitted on every build from the CLI package.json version.
export const CLI_VERSION = '${pkg.version}';
`;

writeFileSync(out, body, 'utf-8');
process.stdout.write(`write-version: ${out} ← ${pkg.version}\n`);
